colorScheme = "alexkb"
defaultAppearance = "light"
showAppearanceSwitcher = false

# Minimal homepage config to use the profile layout.
[homepage]
  layout = "profile"
  showRecent = false

[article]
  showAuthor = false
  showPagination = false
